name: speech_to_text_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # package for icons
  cupertino_icons: ^1.0.0

  # package for http request
  dio: ^4.0.4
  get: ^4.6.1
  # recording words
  speech_to_text: ^3.1.0

  # floating action button effect
  avatar_glow: ^1.2.0

  # launch apps, browser & email
  url_launcher: ^5.7.10

  # copy text to clipboard
  clipboard: ^0.1.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true